// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: xuJ96AwQwiTrZC9DsK4jCu
// Component: orROFCdm_t
import * as React from "react";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Tittle from "../../Tittle"; // plasmic-import: K0hjF132al/component
import Contract from "../../Contract"; // plasmic-import: BqY570oxS4/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_nft_eaze_mint.module.css"; // plasmic-import: xuJ96AwQwiTrZC9DsK4jCu/projectcss
import sty from "./PlasmicDeployContract.module.css"; // plasmic-import: orROFCdm_t/css

export const PlasmicDeployContract__VariantProps = new Array();

export const PlasmicDeployContract__ArgProps = new Array();

function PlasmicDeployContract__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <Tittle
            data-plasmic-name={"tittle"}
            data-plasmic-override={overrides.tittle}
            className={classNames("__wab_instance", sty.tittle)}
          />

          <Contract
            data-plasmic-name={"contract"}
            data-plasmic-override={overrides.contract}
            className={classNames("__wab_instance", sty.contract)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "tittle", "contract"],
  tittle: ["tittle"],
  contract: ["contract"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicDeployContract__ArgProps,
          internalVariantPropNames: PlasmicDeployContract__VariantProps
        }),

      [props, nodeName]
    );

    return PlasmicDeployContract__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDeployContract";
  } else {
    func.displayName = `PlasmicDeployContract.${nodeName}`;
  }
  return func;
}

export const PlasmicDeployContract = Object.assign(
  // Top-level PlasmicDeployContract renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    tittle: makeNodeComponent("tittle"),
    contract: makeNodeComponent("contract"),
    // Metadata about props expected for PlasmicDeployContract
    internalVariantProps: PlasmicDeployContract__VariantProps,
    internalArgProps: PlasmicDeployContract__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicDeployContract;
/* prettier-ignore-end */
