// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicContract } from "./plasmic/nft_eaze_mint/PlasmicContract";
import { createContract } from "../api/NFTCreate";

function Contract_(props, ref) {
  const [name, setName] = React.useState("")
  const [symbol, setSymbol] = React.useState("")

  return (
    <PlasmicContract
      root={{ ref }}
      {...props}

      nameNft={{
        value: name,
        onChange: (n) => setName(n.target.value)
      }}

      symbolNft={{
        value: symbol,
        onChange: (s) => setSymbol(s.target.value)
      }}

      submitButton={{
        onClick: async () => {
          try {
            console.log("valeur: ", name, symbol);
            await createContract(name, symbol);
          } catch (e) {
            console.log(e);
          }
        }
      }}
    />
  );
}

const Contract = React.forwardRef(Contract_);

export default Contract;
