// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicDeployContract } from "./plasmic/nft_eaze_mint/PlasmicDeployContract";

function DeployContract_(props, ref) {

  return <PlasmicDeployContract root={{ ref }} {...props} />;
}

const DeployContract = React.forwardRef(DeployContract_);

export default DeployContract;
