// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicNfTmint } from "./plasmic/nft_eaze_mint/PlasmicNfTmint";
import { MintNFT } from "../api/NFTMint";

function NfTmint_(props, ref) {
  const [metadata, setMetadata] = React.useState("")
  const [address, setAddress] = React.useState("")
  const [contract, setContract] = React.useState("")

  return (
    <PlasmicNfTmint
      root2={{ ref }}
      {...props}

      nftData={{
        value: metadata,
        onChange: (d) => setMetadata(d.target.value)
      }}

      addressInput={{
        value: address,
        onChange: (addr) => setAddress(addr.target.value)
      }}

      contractInput={{
        value: contract,
        onChange: (c) => setContract(c.target.value)
      }}

      mintButton={{
        onClick: async () => {
          try {
            console.log("value: ", metadata, address);
            await MintNFT(metadata, address, contract);
          } catch (e) {
            console.log(e);
          }
        }
      }}
    />);
}

const NfTmint = React.forwardRef(NfTmint_);

export default NfTmint;
